StefanScherer/dockerfiles-windows

openssl/Dockerfile
openssl/README.md

Instead of installing OpenSSL on Windows just use a Windows container. Derived from https://github.com/CenturyLinkLabs/openssl
Example:
```
docker run --rm -e COMMON_NAME=commonname -e KEY_NAME=certprefix -v "$(pwd)\certs:c:\certs" stefanscherer/openssl-windows
```

Create openssl docker image

---

dockertls/Dockerfile
dockertls/README.md

Just a small fun Dockerfile to run the https://github.com/Microsoft/Virtualization-Documentation/tree/master/windows-server-container-tools/DockerTLS script on a Win2016 machine, but without installing OpenSSL directly on that machine. 
```
PS C:\> mkdir certs
PS C:\> docker run -e SERVER_NAME=$(hostname) -e IP_ADDRESSES="192.168.254.135 127.0.0.1" -v "$(pwd)\certs:c:\certs" stefanscherer/dockertls-windows
Creating Certificate Authority Keys
-Creating CA private key
-Creating CA public key
-Certificate Authority Keys Generated
Creating Client Key and Certifcate
-Verifying CA Keys
-Creating client key
-Creating cient certificate request
-Creating extended key use extention file
-Signing client request and generating certificate
-Creating PFX file for Windows
-Clening up extention file and …
```

Create Docker TLS certs in Docker

---

registry/Dockerfile
registry/build.bat
registry/build.sh
registry/build/Dockerfile

Hey, I tried to build the Windows registry on a machine with Windows 10 installed (no VM or other virtualization in-between). I constantly got an error for the `go get github.com/tools/godep` command saying `package github.com/tools/godep: exit status 66`.
This commit works around that issue by catching the error and retrying the same command.
I'm not sure whether this is an issue for me only, but after trying several variants I assume that this workaround won't hurt ;-)
If you have other/better suggestions, please advice, thanks!

work around some strange error while fetching tools/godep

---

quotes/Dockerfile
quotes/README.md

You have to use `\"` to have a double quote `"` in your `RUN` command.
This seems odd coming from Linux, but this is how it works on Windows.
Try the following command in your start menu: press Windows key, then paste the following line and execute the command.
```
powershell -Command $a = \"world\" ; $b = \"hello \"\"$a\"\"\" ; Write-Host \"'$b'\" ; Sleep 5
```
You will see a PowerShell terminal with the output `'hello "world"'`.
That's why you have to write it the same way in your `Dockerfile`
```Dockerfile
RUN powershell -Command $a = \"world\" ; $b = \"hello \"\"$a\"\"\" ; Write-Host \"'$b'\"
```
or with a good practice using the `SHELL` command
```Dockerfile
SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop';"]
RUN $a = \"world\" ; $b = \"hello \"\"$a\"\"\" ; …
```

Understanding quotes

---

PowerShellTricks.md

C:\Users\brycem> measure-command {$(gin).WindowsBuildLabEx}
Seconds           : 42
TotalMilliseconds : 42237.3783
C:\Users\brycem> measure-command {$(gp 'HKLM:\SOFTWARE\Microsoft\Windows
NT\CurrentVersion').BuildLabEx}
Seconds           : 0
TotalMilliseconds : 15.3891

Faster way to get BuildLabString (WinVer info)

---

node/6.9/nano/onbuild/Dockerfile
node/7.2/nano/onbuild/Dockerfile

Change in nano onbuild dockerfiles in order du base docker image on
nanoserver nodejs image instead of windowsservercore image.
Fixes StefanScherer/dockerfiles-windows/issues/31

Fixed nano onbuild Dockerfile

---

build.ps1

`docker rmi` should keep all microsoft/windowsservercore and microsoft/nanoserver base images. 
The previous approach `docker rmi -f $(docker images --filter "since=microsoft/nanoserver" -q)` still removed the newer windowsservercore image.

Improve docker rmi, keeping all base images

---

dockertls/README.md
dockertls/generate-certs.ps1

This change enables you to use the same CA Key for multiple hosts, with the ultimate goal of using the same client certificate for multiple hosts.
The other approach that might be considered would be to separate out the three main phases into separate images.  i.e. First image=CreateCA, Second Image=CreateServerCert, Third Image=CreateClientCert.  But that was a more radical change than I wanted to do without thoughts from others.
Tested=Creating certs for two hosts w/same client and using the image with the existing parameters (i.e. unmodified)

Allow for configuration of multiple hosts with the same CA

---

golang/Dockerfile
golang/build.bat
golang/push.bat

Update Golang to 1.8beta2,
update Git for Windows to 2.11.0

Update golang 1.8beta2, git 2.11.0

---

nodejs-node-8897/README.md
nodejs-node-8897/libuv/Dockerfile
nodejs-node-8897/node/Dockerfile

This `Dockerfile` can be used to compile Node.js from source in a Windows container.
It is used to investigate the bug with Node.js up to 7.3.0 reading files from
a volume mount. I've opened an issue https://github.com/nodejs/node/issues/8897 for discussion.
There also is a first inacceptable proposal https://github.com/nodejs/node/pull/9475 that shows some improvement. But finally this should be fixed in libuv. So let's go down the rabbit hole...

Compile Node.js from source to debug fs.realpathSync()

---

dockertls/Dockerfile

The ftp.openbsd.org website only supports TLS 1.2, as shown in https://www.ssllabs.com/ssltest/analyze.html?d=ftp.openbsd.org
So I remove all the older security protocols and the comment.
The default in a PowerShell terminal shows too old security options, just tested in microsoft/windowsservercore:10.0.14393.567
```
PS C:\> [System.Net.ServicePointManager]::SecurityProtocol
Ssl3, Tls
```
FYI @friism

Use TLS 1.2 for ftp.openbsd.org

---

dockertls/Dockerfile
dockertls/README.md

Switch to nanoserver base image
It seems that the default Invoke-WebRequest in NanoServer supports TLS 1.2.

Build dockertls image with nanoserver

---

golang/Dockerfile
golang/test.bat

The official golang image for nanoserver does not have Git installed. See explanation in https://github.com/docker-library/golang/issues/140
This PR creates a Docker image based on the official and installs Git.

Build nanoserver image with golang and git

---

traefik/Dockerfile
traefik/README.md
traefik/build.bat
traefik/docker-compose.yml
traefik/push.bat
traefik/test.bat
traefik/traefik.toml

Build a nanoserver image with traefik proxy.
The traefik.exe binary is modified to use Docker API version 1.24 instead of 1.21.

Build traefik nanoserver image

---

traefik/Dockerfile
traefik/push.bat

This fixes #75, the patched traefik.exe with the updated Docker API version = 1.24 has been compiled with Travis and pushed to GH releases.

Use binary from Travis build to fix UI

---

appveyor.yml
build.ps1
traefik/Dockerfile
traefik/push.bat
traefik/traefik-dockertls.toml
traefik/traefik-letsencrypt.toml

After the corrections for Windows have been merged into upstream Traefik repo, use the latest upstream binary.

Use upstream traefik binary

---

serverspec/.dockerignore
serverspec/Dockerfile
serverspec/Gemfile
serverspec/Gemfile.lock
serverspec/README.md
serverspec/build.bat
serverspec/push.bat
serverspec/spec/chocolatey_spec.rb
serverspec/spec/ruby_spec.rb
serverspec/test.bat

[Dockerfile](https://github.com/StefanScherer/dockerfiles-windows/blob/master/serverspec/Dockerfile)
This is a Windows Docker image with [Serverspec](http://serverspec.org) installed.
You can run isolated Serverspec tests in Windows containers, eg. to test all
scenarios of an own built MSI package.
Each container starts without your MSI package installed, so you don't need
a snapshot of your VM.
To run the Serverspec tests create a folder `spec` with some `*_spec.rb` files.
See the [spec](https://github.com/StefanScherer/dockerfiles-windows/tree/master/serverspec/spec) folder to selftest this Docker image for an example.
Run the container like this:
```
PS C:\> docker run -v "$(pwd)/spec:C:/spec" stefanscherer/serverspec-windows
Chocolatey
File "C:\ProgramData/chocolatey/bin"
should exist …
```

Build a Serverspec base image for Windows

---

traefik/Dockerfile
traefik/push.bat

- Update Traefik 1.2.0-rc2
- Cleanup Dockerfile, no mapped drives needed

Update Traefik 1.2.0-rc2

---

traefik/Dockerfile

Change the path to the configfile from T: to C:/etc/traefik as there is no need for the drive subtitution.

Fix configfile path for traefik

---

node/4.8/Dockerfile
node/4.8/README.md
node/4.8/nano/Dockerfile
node/4.8/nano/onbuild/Dockerfile
node/4.8/onbuild/Dockerfile
node/6.10/Dockerfile
node/6.10/README.md
node/6.10/nano/Dockerfile
node/6.10/nano/onbuild/Dockerfile
node/6.10/onbuild/Dockerfile
node/7.8/Dockerfile
node/7.8/nano/Dockerfile
node/build.ps1
node/push.ps1
node/test.ps1
node/update.sh

To get rid of maintaining the sha256 checksums for each version of Node.js it would be better to use gpg signature checks as it is done for the Linux Docker images (eg. [nodejs/docker-node/7.8/Dockerfile](https://github.com/nodejs/docker-node/blob/74e5c8fec424379cdf3bd9bf44d46c5c07899ddb/7.8/Dockerfile)).
Install gpg on Windows isn't that easy and uninstalling the files and package would complicate the Dockerfile. 
multi-stage build for the rescue
Let's try it with AppVeyor.
This is a proof-of-concept for https://github.com/nodejs/docker-node/pull/362

Update Node 4.8.2, 6.10.2 + Use gpg signature check and multi-stage build

---

php/Dockerfile

Rather than waiting an arbitrary amout of time, we can use the Start-Process cmdlet and tell it to wait for the process to finish. I've used this with other Dockerfiles, including ones with msiexec commands, and it seems to do the job !

Cleaner way to wait for vc_redist installation to finish

---

dockertls/generate-certs.ps1
dockertls/run.ps1

Had some minutes before DockerCon to add the serverName to the subjectAltName to make docker-compose work with the certs.
Tested it with the small `run.ps1` and two environment variables FQDN and PUBIP.
```powershell
if (!(Test-Path ~\.docker)) {
mkdir ~\.docker
}
$ips = ((Get-NetIPAddress -AddressFamily IPv4).IPAddress) -Join ','
docker container run --rm `
-e SERVER_NAME=$env:FQDN `
-e IP_ADDRESSES=$ips,$env:PUBIP `
-v "C:\ProgramData\docker:C:\ProgramData\docker" `
-v "$env:USERPROFILE\.docker:C:\Users\ContainerAdministrator\.docker" `
stefanscherer/dockertls-windows
```
Fixes #99

Add servername to subjectAltName for docker-compose

---

mongo/3.4/build.ps1
node/build.ps1
registry/build.ps1
update-docker-rc.ps1
webserver/build.ps1

Instead of using master (nightly) binaries, switch over to 17.05.0-rc1 binaries.

Use one script to update to Docker 17.05.0-rc1

---

golang-issue-18555/Dockerfile
golang-issue-18555/README.md
golang-issue-18555/build.ps1
golang-issue-18555/test.ps1

Add test for golang/go#18555 to see if latest Go sources have a fix for compiling sources directly in a volume mountpoint.

Add test for golang/go#18555

---

caddy/Dockerfile
caddy/build.ps1
caddy/push.ps1
caddy/test.ps1

For easier maintenance, read the CADDY_VERSION From Dockerfile so we only have to update one place for new caddy versions.

Read CADDY_VERSION from Dockerfile

---

golang/Dockerfile.devel
golang/build.ps1
golang/push.ps1
golang/test.ps1

After golang/go#18555 got fixed with https://github.com/golang/go/commit/53003621720ff39c4745a76f76847123c27b01ea let's build a Windows Docker image with golang built from master.
Images are available on the Docker Hub:
* stefanscherer/golang-windows:1.8, stefanscherer/golang-windows:latest
* stefanscherer/golang-windows:devel

Build devel version of Golang to test fix for #18555

---

appveyor.yml
git-for-windows-issue/README.md
golang/Dockerfile
golang/Dockerfile.devel

Update golang image with git-for-windows 2.13.0 which seems to work with bind-mounted volumes into a Windows container.

Update git-for-windows 2.13.0

---

dockertls/generate-certs.ps1
dockertls/run.ps1
dockertls/test.ps1

**Use Case:**
WHEN a common DNS name exists for all managers in a swarm (e.g. manager.nonprod.blah.io)
AND each node must support communication using the following DNS name examples
COMPUTERNAME
COMPUTERNAME.ACTIVE_DIRECTORY_DOMAIN
manager.nonprod.blah.io
AND each node in the swarm has DockerTLS enabled using the stefanscherer/dockertls-windows image
THEN `dockerhost -H COMPUTERNAME ps` should execute successfully
AND `dockerhost -H COMPUTERNAME.ACTIVE_DIRECTORY_DOMAIN ps` should execute successfully
AND `dockerhost -H manager.nonprod.blah.io ps` should execute successfully.
**Changes Made**
- Added an environment variable, named `ALTERNATIVE_NAMES`, to supply a comma-delimited list of alternative names.
- Refactored logic that generated Subject Alternative Names to support generation of …

[Enhancement] Add support for multiple dns names in the SAN of the generated certificate.

---

golang-issue-21867/Dockerfile
golang-issue-21867/Dockerfile.works
golang-issue-21867/README.md
golang-issue-21867/currentuser.go

Investigations for issue https://github.com/golang/go/issues/21867
Some Golang binaries are not able to run in microsoft/nanoserver-insider images as there is an indirect dependency to the missing netapi32.dll.
```
$ docker build -t currentuser .
$ docker run currentuser
Hello
panic: Failed to load netapi32.dll: The specified module could not be found.
goroutine 1 [running]:
syscall.(*LazyProc).mustFind(0xc04203b8c0)
C:/go/src/syscall/dll_windows.go:280 +0x5f
syscall.(*LazyProc).Addr(0xc04203b8c0, 0x1)
C:/go/src/syscall/dll_windows.go:287 +0x32
syscall.NetGetJoinInformation(0x0, 0xc04205fca8, 0xc04205fca4, 0x0, 0x0)
C:/go/src/syscall/zsyscall_windows.go:1784 +0x38
os/user.isDomainJoined(0x4623e4, 0x29f8600, 0x0)
C:/go/src/os/user/lookup_windows.go:21 +0x5a …
```

Example for golang/go#21867

---

dockertls/README.md
dockertls/generate-certs.ps1

I have run into a scenario where I have `dockerd` configured with the `--data-root <Path>` option.  When I run this container to secure my site I am unable to restart docker until I edit the paths of the certificate in the daemon.json file.
This change adds support to provide a custom Docker Data root path for writing into the configuration file.
This change also adds missing documentation for the ALTERNATIVE_NAMES environment variable.

Add support for a custom Docker Data-Root directory.  Update readme.md.

---

node/8.6/README.md
node/8.6/build-tools/Dockerfile
node/build.ps1
node/push.ps1

Add a Node.js image with the Windows build tools installed.
With a multi-stage build you then can install NPM dependencies and even compile native bindings.
```Dockerfile
FROM stefanscherer/node-windows:8.6.0-build-tools
WORKDIR /code
COPY package.json package.json
RUN npm install
COPY . .
FROM stefanscherer/node-windows:8.6.0-nano
COPY --from=0 /code /code
WORKDIR /code
ENTRYPOINT ["node.exe", "app.js]
```

Add build-tools image

---

curl/Dockerfile
curl/Dockerfile.1709
curl/README.md
curl/push.ps1

Create a minimal curl image based in microsoft/nanoserver.
And rebase it to 1709 to have a nanoserver:1709 image + curl to download things without PowerShell.

Minimize curl + 1709 version

---

curl/Dockerfile.1709
curl/README.md
curl/manifest.yml
curl/push.ps1

Create a manifest list with both Windows versions
```
docker run stefanscherer/curl-windows
```
Works on Windows Server 2016 LTSC and 1709 picking the right image without the need of a HyperV container.

Create multi-os curl image

---

node/test.ps1

* Check for exit code of node and npm command
* Check for expected node version string
* Check at least that output of npm is not empty
This helps to find problems in nanoserver earlier, see nodejs/node/issues/16603

Improve Node.js tests running commands in container

---

docker-cli/Dockerfile
docker-cli/README.md
docker-cli/build.ps1
docker-cli/push.ps1

* Update Docker CLI 17.10.0-ce
* Build multi-os image for Windows Server 2016 + Windows Server 1709
Example for Windows Server 1709:
```
docker run -v //./pipe/docker_engine://./pipe/docker_engine -u ContainerAdministrator stefanscherer/docker-cli-windows docker version
```

Update Docker CLI 17.10.0-ce

---

traefik/Dockerfile

Update Traefik 1.4.2
No multi-os image as traefik.exe does not work in insider and 1709 nanoserver image as netapi32.dll is missing. Golang has to be fixed https://github.com/golang/go/issues/21867

Update Traefik 1.4.2

---

java/openjdk/ojdkbuild/nanoserver/Dockerfile

This will allow building for windows server 1709 and up, which no longer
has powershell inside nanoserver.
Example for building on server 1709:
```
docker build --build-arg WINDOWS_DOCKER_TAG=1709 .
```
I've built a 1709 version here: [freakingawesome/java:8-nanoserver-1709](https://hub.docker.com/r/freakingawesome/java/tags/)

Use multi-stage build for ojdkbuild nanoserver

---

git-for-windows-issue/Dockerfile
git-for-windows-issue/README.md
git-for-windows-issue/run-test-2-in-volume.ps1
git-for-windows-issue/run-test-3-in-volume-currdir.ps1
git-for-windows-issue/run-test-4-in-volume-subdir.ps1

The MinGit BusyBox ZIP solves the problem to use `git clone` in a bind mounted volume.

Use MinGit to make git work in mapped volumes

---

poshspec/Dockerfile
poshspec/README.md
poshspec/build.ps1
poshspec/push.ps1
poshspec/spec/container.ps1
poshspec/test.ps1

Try poshspec in a Windows container to replace some serverspec tests with it and see how it works without that Ruby, bundler, Gemfile overhead for Windows infrastructure tests.

Add poshspec

---

node-example/.vscode/launch.json
node-example/Dockerfile
node-example/README.md
node-example/app.js
node-example/docker-compose.yml
node-example/package-lock.json
node-example/package.json
node-example/test.js
node/9.4/Dockerfile.insider

The latest Windows Insider Server Preview 17074 comes with a great new feature.
The mounted volumes are "real" folders inside the container and no longer a symlink to "ContainerMappedDirectories" share which disturbed Node.js finding files.

Update nodemon debug scenario for Insider 17074

---

nodew/Dockerfile
nodew/README.md

A console-less node.exe
Although this `nodew.exe` is not needed inside a container, this is a
containerized way to produce one without installing other tools on you host
machine.
```
docker build -t nodew .
docker create nodew
docker cp $(docker ps -ql):/home/.nvm$/this/nodew.exe nodew.exe
```
Running the `nvm$ install 8.9.4` command results in an error during extracing
the MSI package. The reason is that msiexec cannot handle long paths:
```
C:\Users\ContainerAdministrator\AppData\Local\Temp>type MSI50547.LOG
Error 1320. The specified path is too long: C:\Users\ContainerAdministrator\.nvm$\.CGe\nodejs\node_modules\npm\node_modules\pacote\node_modules\make-fetch-happen\node_modules\https-proxy-agent\node_modules\agent-base\node_modules\es6-promisify\node_modules\es6-promise\lib\es6-promise …
```

Build console-less nodew.exe

---

procmon/Dockerfile
procmon/Dockerfile.insider
procmon/README.md

Try to run procmon - the Sysinternals Process Monitor - in a container.
```
docker build -t procmon .
```
With `procmon /quiet /minimized /backingfile abc.pml` you can start capturing.
With `procmon /terminate` you can stop capturing.
The captured file doesn't look good. It starts with 4,194,304 byte, after
terminating the capture the file is only 976 byte. This happens in 17093 insider builds.
In a 10.14393.2007 windowsservercore image the file is 4,194,304 byte, but also doesn't look good.
/cc @konstantinpae FYI

Try procmon in a container

---

golang-netapi-helper/Dockerfile
golang-netapi-helper/README.md
golang-netapi-helper/build.sh
golang-netapi-helper/push.sh

If you want to run a Golang binary in a NanoServer container 1709 or newer you might run into trouble with a missing `netapi32.dll` DLL.
The work in progress to fix this in a future version of Golang can be found at https://github.com/golang/go/issues/21867
As a workaround use this image which has a copy of the DLL from the Server Core base image.

Add netapi-helper image for some golang binaries

---

swarm/build.ps1
swarm/push.ps1
swarm/test.ps1

Use rebase-docker-image 0.3.0 to rebase the 2016 swarm image to 1709 including the missing netapi32.dll from a helper image.
Build manifest list for 2016 + 1709.
Improvement for #269 to build everything on AppVeyor.
Workaround for https://github.com/golang/go/issues/21867

Build swarm 1709 image with netapi32.dll

---

traefik/push.ps1

Use rebase-docker-image 0.3.0 to rebase the 2016 traefik image to 1709 including the missing netapi32.dll from a helper image.
Build manifest list for 2016 + 1709.
Workaround for https://github.com/golang/go/issues/21867

Build Traefik 1709 image with netapi32.dll

---

swarm/Dockerfile
swarm/Dockerfile.1709
swarm/build.ps1
swarm/push.ps1
swarm/test.ps1

The line
```Dockerfile
COPY --from=build /go/src/github.com/docker/swarm/swarm.exe /swarm.exe
```
was wrong as it copied the old `swarm.exe` from the GitHub repo. The compiled `swarm.exe` 1.2.8 can be found at `/go/bin/swarm.exe`. Ping @gamma ;-)
Added a test to check the correct version of swarm.exe
Fixed Docker tag, removed `v`
Build the multi-os image on AppVeyor.

Copy correct swarm binary to final stage

---

compose/lcow/README.md
compose/lcow/docker-compose.yml

In LCOW mode it is possible to use `docker-compose` to mix Linux and Windows containers.
I had to cheat a little bit.
Pre-pull the Linux image with the `--platform` option.
```
docker pull --platform linux tutum/curl:alpine
```
```
docker-compose up
```
The hosts table does not have the `win` machine.
In a different terminal run
```
docker inspect lcow_win_1
```
Fetch the IPAddress of the Window container. Now enter the Linux container and append the `win` container to the hosts table.
```
docker-compose exec lin sh
echo "1.2.3.4 win" >> /etc/hosts
```

Small LCOW example with docker-compose

---

docker-cli/Dockerfile
docker-cli/push.ps1

The docker.exe also uses glog and crashes in microsoft/nanoserver:1709 container.
Use the netapi-helper base image for the rebase step.

Fix docker-cli 1709 image

---

node/10.0/Dockerfile
node/10.0/nano/Dockerfile
node/8.11/Dockerfile
node/8.11/nano/Dockerfile
node/push.ps1

Build manifest list for Node.js 10.0.0 image for Windows Server 2016, version 1709 and version 1803.

Build Node.js image for 1803

---

docker-cli/Dockerfile
docker-cli/push.ps1

Build multi-os image with Docker CLI for 2016, 1709 and 1803.

Build Docker CLI image for 1803

---

webserver/.dockerignore
webserver/Dockerfile.insider

The default user ContainerUser is weird, golang cannot write webserver.exe into /code folder
```
$ docker build -t stefanscherer/webserver-windows:0.2.1-10.0.17744.1001 -f Dockerfile.insider .
Sending build context to Docker daemon   6.07MB
Step 1/8 : FROM stefanscherer/golang-windows:1.11-10.0.17744.1001 as gobuild
---> cdccbbfc5976
Step 2/8 : COPY . /code
---> Using cache
---> 9a47ba44eddc
Step 3/8 : WORKDIR /code
---> Using cache
---> 8a385309a03b
Step 4/8 : RUN go build webserver.go
---> Running in b28c91bd7fa1
go build command-line-arguments: open webserver.exe: Access is denied.
The command 'cmd /S /C go build webserver.go' returned a non-zero code: 1
```
I have to add `USER ContainerAdministrator` again to make it work:
```
$ docker build -t …
```

Build webserver with 17744 insider

---

portainer/Dockerfile.insider

Build Portainer 1.19.1 for nanoserver-insider:10.0.17744.1001 base image

Build portainer image for insider 17744

---

appveyor.yml
node/10/Dockerfile
node/10/README.md
node/10/build-tools/Dockerfile
node/10/build-tools/Dockerfile.insider
node/10/nano/Dockerfile
node/10/nano/Dockerfile.insider
node/10/pure/Dockerfile
node/10/pure/Dockerfile.insider
node/build.ps1
node/push.ps1
node/test.ps1

- Update Node.js 10.12.0
- Update Yarn 1.10.1
- Update Git 2.19.1 (as the release notes mentions it should include Git LFS)
- Add Windows Server 2019 variant to the manifest list

Update Node.js 10.12.0

---

traefik/Dockerfile
traefik/Dockerfile.1709
traefik/Dockerfile.1803
traefik/Dockerfile.insider
traefik/push.ps1
traefik/test.ps1

Create a Windows Traefik image with a manifest-list for 2016, 1709, 1803 and 1809/2019

Update Traefik 1.7.4, add 1809 to manifest-list

---

node/10/nano/Dockerfile

The MinGit version of git seems to have incompatibilities with windows
since some commands as submodules are still implemented as Unix shell scripts:
https://github.com/git-for-windows/git/issues/1303#issuecomment-354977460
This solves bug  #372 on nanoserver 2016/1709/1803

use MinGit-busybox flavor of git instead of MinGit one.

---

traefik/docker-compose.yml

As Traefik looks now working with named pipes I think that it is better to use it on example configs.

Updated Traefik example to use named pipe

---

traefik/README.md
traefik/docker-compose.yml
traefik/traefik.toml

Update the docker-compose example for Traefik with a simple http frontend load-balancing two instances of whoami.
Follow-up of #379

Update Traefik docker-compose example

---

traefik/docker-compose.yml

Run `traefik.exe` in process isolation mode to make the example docker-compose.yml work on Windows 10 1809 with Docker-Desktop 2.0.0.2 (Docker 18.09.1). This combination allows process isolation on Windows 10 as well.
This helps until https://github.com/containous/traefik/issues/4409 get fixed.
Fixes #383

Run traefik in process isolation mode

---

netapi-helper/build.sh

When building a new version of the netapi-helper image, also pull the servercore image.

Also pull servercore image

---

appveyor.yml
traefik/build.ps1
traefik/push.ps1

- Switch to private beta "Windows Server 2019"
- Adjust Traefik image build and manifest list without the rebase-docker-image tool.

Testdrive 2019, build Traefik for 1803 and 1809

---

dockertls/Dockerfile
dockertls/Dockerfile.1709
dockertls/Dockerfile.1809
dockertls/README.md
dockertls/generate-certs.ps1
dockertls/run.ps1

To reduce overall container size by a factor of 10, I reconfigured the Dockerfile to pull the nanoserver build of PowerShell Core, updated the generate-certs.ps1 to add LibreSSL to the path at the start of the script (so we didn't hit compatibility issues w/ PowerSell 6.2) and updated the scripts & README to reflect the container running under the containeruser context instead of containeradministrator.
The Dockerfile uses powershell:nanoserver-1809 as the base image (needed for AppVeyor to succeed)

Switched to Nanoserver for smaller images

---

check-baseimage/Dockerfile
check-baseimage/README.md
check-baseimage/check-baseimage.ps1

I started with this gist https://gist.github.com/StefanScherer/de02a89b4d6ea0e330678c222b4e8270 to check if a Windows Server is up to date.
Then I thought, ok that small script can also be used during a `docker build` or in an entrypoint during runtime of a Windows container to check if we're using an up to date base image.

Check base image version

---

compose/in-docker/Dockerfile
compose/in-docker/README.md
compose/in-docker/docker-compose.yml
compose/in-docker/run.sh

Run docker-compose in a windows container.
This PR is to test https://github.com/docker/docker-py/pull/2421 
It installs docker-compose with pip and replaces the npipesocket.py with the one from the pull request.
Without that change I get
```
$ docker run -v //./pipe/docker_engine://./pipe/docker_engine -it compose-in-docker docker-compose up
ERROR: Couldn't connect to Docker daemon. You might need to start Docker for Windows. 
```
With the change I get
```
$ docker run -v //./pipe/docker_engine://./pipe/docker_engine -it compose-in-docker docker-compose up
Creating test_whoami_1 ... done                                                                                
Attaching to test_whoami_1                                                                                     
whoami_1  | …
```

Run docker-compose in docker

---

dotnet/Dockerfile
dotnet/Dockerfile.orig
dotnet/README.md

This Dockerfile builds a Windows image (the big one, not Windows Server Core) with .NET Framework 4.8.
The Dockerfile is based on https://github.com/microsoft/dotnet-framework-docker/blob/master/4.8/runtime/windowsservercore-ltsc2019/Dockerfile
with a few changes
```diff
3c3
< FROM mcr.microsoft.com/windows/servercore:ltsc2019
---
> FROM mcr.microsoft.com/windows:1809
4a5
> USER ContainerAdministrator
```
The main difference is that the big Windows image has the default user ContainerUser instead of ContainerAdministrator and therefore does not have enough permission to install software.

Add .NET Framework on Windows example

---

node/12/Dockerfile

After some trial and error, I've added these missing configurations to install `node-gyp` based packages. See issue #440

Update Dockerfile to support node-gyp

---

apache/Dockerfile

The link for downloading apache was broken, and I also updated the windows server version to ltsc2019

Updated apache-windows image
