- dockertls/Dockerfile
- dockertls/openssl.cnf
@StefanScherer we shouldn't use antediluvian openssl which is barely supported
> use libressl

- dockertls/Dockerfile
> remove pdb files

- chocolatey/Dockerfile
- chocolatey/build.sh
- chocolatey/push.sh
A `FROM chocolatey` base image :-)
> Build a Chocolatey base image

- elasticsearch/README.md
- elasticsearch/build.sh
- elasticsearch/nanoserver/Dockerfile
- elasticsearch/windowsservercore/Dockerfile
First working version of Elasticsearch in a Windows Docker image.
Works both in windowsservercore and nanoserver.
> Add Elasticsearch

- consul/Dockerfile
- consul/build.bat
- consul/build.sh
Switch to smaller base image microsoft/nanoserver,
update to Consul version 0.7.1
> Update Consul 0.7.1, switch to nanoserver

- msbuild/Dockerfile
- msbuild/README.md
- msbuild/entrypoint.bat
Local copy of the PR https://github.com/Microsoft/Virtualization-Documentation/pull/492 to create a `microsoft/msbuild` image.
> Add msbuild image to compile some C++ solutions

- node/4.6/nano/Dockerfile
- node/6.9/nano/Dockerfile
- node/7.2/nano/Dockerfile
As mentioned in #32 `Expand-Archive` should work in nanoserver. Let's test this with this PR.
> Use Expand-Archive in nanoserver

- php/Dockerfile
- php/build.bat
- php/config/configure_iis.ps1
- php/run.bat
- php/stage/php/composer.bat
- php/stage/php/php.ini
- php/stage/php/run.bat
- php/stage/www/index.php
- php/stage/www/phpinfo.php
- php/stage/www/web.config
- Fixes #39 
- Installs PHP 7.1.0
- Installs `composer` (PHP package manager)
- Configures IIS w/ FastCGI
- Adds a site at `C:\www`
> PHP FastCGI + IIS

- build.ps1
- java/openjdk/ojdkbuild/build.bat
- java/openjdk/ojdkbuild/nanoserver/Dockerfile
- java/openjdk/ojdkbuild/push.bat
- java/openjdk/ojdkbuild/windowsservercore/Dockerfile
Signed-off-by: Stefan Scherer <scherer_stefan@icloud.com>
> Update openjdk 1.8.0.111-3.b15

- consul/Dockerfile
- consul/build.bat
- consul/build.sh
- consul/push.bat
Update Consul to version 0.7.2
> Update Consul 0.7.2

- dockertls/README.md
- dockertls/generate-certs.ps1
In addition you can create a configuration for `docker-machine`. The container then writes the TLS certs into a sub directory `machine\machines\$env:MACHINE_NAME` in your `.docker` directory and creates a `config.json` with absolute pathes using `$env:MACHHINE_HOME` environment variable. So you can build a Docker machine configuration for eg. your MacBook with Unix pathes.
```powershell
mkdir $env:USERPROFILE\.docker
docker run --rm `
-e SERVER_NAME=$(hostname) `
-e IP_ADDRESSES=127.0.0.1,192.168.254.135 `
-e MACHINE_NAME=windows `
-e MACHINE_HOME=/Users/you `
-e MACHINE_IP=192.168.254.135 `
-v "c:\programdata\docker:c:\programdata\docker" `
-v "$env:USERPROFILE\.docker:c:\users\containeradministrator\.docker" stefanscherer/dockertls-windows
```
Closes #16
> Optionally create docker machine config.json

- node/4.7/Dockerfile
- node/4.7/README.md
- node/4.7/nano/Dockerfile
- node/4.7/nano/onbuild/Dockerfile
- node/4.7/onbuild/Dockerfile
- node/6.9/Dockerfile
- node/6.9/README.md
- node/6.9/nano/Dockerfile
- node/6.9/nano/onbuild/Dockerfile
- node/6.9/onbuild/Dockerfile
- node/build.bat
- node/push.bat
- node/test.bat
- node/update.sh
Signed-off-by: Stefan Scherer <scherer_stefan@icloud.com>
> Update Node.js 4.7.2 and 6.9.4

- dockertls/Dockerfile
- dockertls/push.bat
- dockertls/test.bat
Use latest stable release of LibreSSL, this is version 2.4.4 and not 2.5.0
> Use LibreSSL 2.4.4 stable

- nanoserverapiscan/build.bat
- nanoserverapiscan/push.bat
- nanoserverapiscan/test.bat
Build nanoserverapiscan image with AppVeyor
> Build nanoserverapiscan image with AppVeyor

- registry/build.bat
- registry/build/Dockerfile
- registry/push.bat
Signed-off-by: Stefan Scherer <scherer_stefan@icloud.com>
> Update registry 2.6.0

- chocolatey/build.bat
- chocolatey/push.bat
- chocolatey/test.bat
Build a chocolatey Docker image for local Chocolatey package builds and tests.
You may use this to build Chocolatey packages on a Mac with a [Windows docker machine](https://github.com/StefanScherer/windows-docker-machine).
```bash
docker run -v C:$(pwd):C:/choco stefanscherer/chocolatey powershell -Command 'cd c:\choco ; choco pack ; .\test.ps1'
```
> Build chocolatey image

- docker-cli/Dockerfile
- docker-cli/build.bat
- docker-cli/push.bat
- docker-cli/test.bat
Create a Windows image with the Docker client for some tests to communicate with the Windows Docker engine on Win10/Win2016 from inside a container.
> Build Windows image with Docker client

- traefik/README.md
- traefik/docker-compose.yml
- traefik/traefik.toml
Playing with Traefik and Let's Encrypt.
> Try traefik with Let's Encrypt

- appveyor.yml
Test updating to Docker 1.13.1 CS.
Issues:
- Update takes two minutes in AppVeyor
- After the update I have to manually start the Docker service. Opened issue https://github.com/OneGet/MicrosoftDockerProvider/issues/17
> Test docker update

- appveyor.yml
Use the official AppVeyor builder Visual Studio 2017 that has Docker and Windows base Docker images installed.
> Use official AppVeyor builder w/ Docker

- golang/Dockerfile
- golang/build.bat
- golang/push.bat
updated the version to 2.12.0 and added a simple verification for the the downloaded file against the expected SHA
> bumping git version and adding hash validation

- jenkins/.gitignore
- jenkins/Dockerfile
- jenkins/README.md
- jenkins/build.bat
```bash
$ docker build -t jenkins .
$ mkdir jenkinsdata
$ docker run -it -p 8080:8080 -v C:$(pwd)/jenkinsdata:C:/jenkins jenkins
$ open http://$(docker-machine ip windows):8080
```
> Add Jenkins 2.50

- traefik/Dockerfile
- traefik/push.bat
Update to the official release 1.2.0 of Traefik.
> Update Traefik 1.2.0

- consul/Dockerfile
- consul/build.ps1
- consul/push.ps1
- consul/test.ps1
Put the latest release candidate of Consul into a Windows Docker image.
fixes #110
> Update consul 0.8.0-rc1

- php/Dockerfile
Inspired from the chocolatey PHP package. It's a bit hacky in my opinion, but it should work (script tested entirely using Powershell in OS X !)
> Dynamically get latest PHP version

- caddy/Dockerfile
- caddy/README.md
- caddy/build.ps1
- caddy/conf/Caddyfile
- caddy/push.ps1
- caddy/test.ps1
- caddy/www/index.html
Image for running the awesome standalone webserver caddy - https://caddyserver.com
> adding image for caddy version 0.10

- caddy/README.md
- caddy/test.ps1
- caddy/www/index.html
Updating the README and tests to give a little more information and some examples. Tests now check for working http response rather than just displaying the logs.
> updating README and tests

- mongo/3.4/enterprise/Dockerfile
- mongo/3.4/enterprise/build.ps1
- mongo/3.4/enterprise/test.ps1
- mongo/3.4/push.ps1
- update-docker-rc.ps1
* Update community edition to MongoDB 3.4.4
* Add a Dockerfile for MongoDB enterprise. There is missing `wininet.dll`, so just cherry-pick it from windowsservercore
> Update mongo 3.4.4

- registry/Dockerfile
Use the devel version of Golang to have the fix for Windows volumes compiled into golang binaries.
Should help in #143
> Use golang:devel with the fix for windows volumes

- chocolatey/build.ps1
- chocolatey/push.ps1
Build docker image with chocolatey 0.10.7
fixes #169
> Update chocolatey 0.10.7

- registry/README.md
To encourage easy adoption, I would first show the insecure (but easy) way and then the secure (but a bit more complicated) way
> Add documentation about running a secured registry

- traefik/Dockerfile
Traefik has released version 1.3.5.  Updating dockerfile to reflect that release.
> Update Traefik Version to 1.3.5 from 1.3.4

- caddy/Dockerfile
- caddy/conf/Caddyfile
Update Caddy 0.10.1, check if it still works.
> Update caddy 0.10.7

- serverspec/spec/chocolatey_spec.rb
- serverspec/spec/ruby_spec.rb
- serverspec/test.ps1
Add exit code check in Serverspec test to abort AppVeyor build.
> Improve serverspec image

- README.md
the link was giving king of 404 error on msdn
> fix documentation Quick Start link

- busybox/Dockerfile
- busybox/Dockerfile.1709
- busybox/README.md
- busybox/build.ps1
- busybox/push.ps1
- busybox/test.ps1
Create a nanoserver image with busybox + curl to have a good enough and still small enough nanoserver image for Windows Server 2016 LTSC + 1709.
> Add busybox 64bit for nanoserver + 1709

- consul/Dockerfile
- consul/README.md
- consul/manifest.yml
- consul/push.ps1
* Update Consul 1.0.0
* Update README, fixes #225
* Make multi-os image for 2016 and 1709
> Update Consul 1.0.0

- prometheus/Dockerfile
- prometheus/push.ps1
* Update Prometheus 1.8.1
* Build multi-os image for Windows Server 2016 and Windows Server 1709
> Update Prometheus 1.8.1

- registry/README.md
- registry/push.ps1
Build registry 2.6.2 as multi-os image for Windows Server 2016 and Windows Server 1709.
> Build multi-os registry image

- node-hello-express/.dockerignore
- node-hello-express/.editorconfig
- node-hello-express/.gitignore
- node-hello-express/Dockerfile
- node-hello-express/Dockerfile.core
- node-hello-express/Dockerfile.nano
- node-hello-express/app.js
- node-hello-express/build.bat
- node-hello-express/build.ps1
- node-hello-express/package.json
- node-hello-express/roboter.js
Fix an old Node.js hello example as GitHub notified me about this:
The ejs dependency defined in package.json has a known moderate severity security vulnerability in version range < 2.5.5 and should be updated.
Nice feature, thanks GitHub 👍
> Fix potential vulnerability in ejs dependency

- registry/build.ps1
- registry/push.ps1
- registry/test.ps1
Fix registry version tag v2.6.2 -> 2.6.2
> Fix registry tags to push manifest-list

- traefik/Dockerfile
- traefik/Dockerfile.1709
- traefik/insider/Dockerfile
Update base image to 1884,
update Traefik 1.4.4
> Update Traefik 1.4.4

- node/6.12/Dockerfile
- node/6.12/nano/Dockerfile
- node/8.9/Dockerfile
- node/8.9/Dockerfile.1709
- node/8.9/Dockerfile.insider
- node/8.9/nano/Dockerfile
- node/8.9/nano/Dockerfile.1709
- node/8.9/nano/Dockerfile.insider
- node/9.3/Dockerfile
- node/9.3/Dockerfile.insider
- node/9.3/nano/Dockerfile
- node/9.3/nano/Dockerfile.1709
- node/9.3/nano/Dockerfile.insider
The New-Item command created a file instead of a folder. Anyway this
folder wouldn't be used.
> Fixes #236 - Clean node PATH

- node/4.8/Dockerfile
- node/4.8/nano/Dockerfile
- node/6.12/Dockerfile
- node/6.12/README.md
- node/6.12/nano/Dockerfile
- node/8.9/Dockerfile
- node/8.9/Dockerfile.1709
- node/8.9/Dockerfile.insider
- node/8.9/README.md
- node/8.9/build-tools/Dockerfile
- node/8.9/build-tools/Dockerfile.insider
- node/8.9/nano/Dockerfile
- node/8.9/nano/Dockerfile.1709
- node/8.9/nano/Dockerfile.insider
- node/9.3/Dockerfile
- node/9.3/Dockerfile.1709
- node/9.3/Dockerfile.insider
- node/9.3/nano/Dockerfile
- node/9.3/nano/Dockerfile.1709
- node/9.3/nano/Dockerfile.insider
- node/build.ps1
- node/push.ps1
- node/test.ps1
Update Node.js 8.9.4, 6.12.3
Update GPG 2.3.4
> Update Node.js 8.9.4, 6.12.3

- node/4.8/Dockerfile
- node/4.8/nano/Dockerfile
- node/6.12/Dockerfile
- node/6.12/nano/Dockerfile
- node/8.9/Dockerfile
- node/8.9/Dockerfile.1709
- node/8.9/nano/Dockerfile
- node/8.9/nano/Dockerfile.1709
- node/9.3/Dockerfile
- node/9.3/Dockerfile.1709
- node/9.3/nano/Dockerfile
- node/9.3/nano/Dockerfile.1709
Update base image for all Node.js Windows images.
> Update base image for node

- powercli/Dockerfile
- powercli/README.md
- powercli/build.ps1
- powercli/push.ps1
- powercli/test.ps1
To play with PowerCLI with vCloud Director I put it into a Windows container.
> Add PowerCLI for Windows

- swarm/Dockerfile
- swarm/Dockerfile.1709
Not sure if the build files should be updated as well ...
> Add 1709 Swarm Dockerfile

- node/6.13/Dockerfile
- node/6.13/nano/Dockerfile
- node/8.9/Dockerfile
- node/8.9/Dockerfile.1709
- node/8.9/Dockerfile.insider
- node/8.9/nano/Dockerfile
- node/8.9/nano/Dockerfile.1709
- node/8.9/nano/Dockerfile.insider
- node/9.7/Dockerfile
- node/9.7/Dockerfile.1709
- node/9.7/Dockerfile.insider
- node/9.7/nano/Dockerfile
- node/9.7/nano/Dockerfile.1709
- node/9.7/nano/Dockerfile.insider
- node/test.ps1
Add Yarn 1.5.1 to Docker images. 
Fixes #286
> Add Yarn 1.5.1

- consul/Dockerfile
- consul/push.ps1
- deploy.ps1
- update-docker-cli.ps1
* Update Consul 1.0.6
* Use Docker CLI 18.02.0-ce for manifest command
* Remove CircleCI artifact download
> Update Consul 1.0.6

- busybox/Dockerfile
Test multi-os curl image after fixing order of manifest list entries.
> Update curl image

- netapi-helper/Dockerfile.1803
- netapi-helper/build.sh
- traefik/Dockerfile
- traefik/Dockerfile.1709
- traefik/insider/Dockerfile
- traefik/push.ps1
- Update Traefik 1.6.1
- Update base image
- Add 1803 variant
> Update Traefik 1.6.1

- dockertls/Dockerfile
- dockertls/README.md
- dockertls/generate-certs.ps1
Allow user to specify expiry days for the generated CA and certs (defaults to 365).
> Add environment variable for SSL expiry days & update Dockerfile

- spooler/Dockerfile
- spooler/README.md
Here is an example to enable the Windows spooler service.
```
$ cat Dockerfile 
FROM mcr.microsoft.com/windows-insider
SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]
RUN Set-Service -Name spooler -StartupType Automatic
RUN Get-Printer
~/code/dockerfiles-windows/spooler on master
$ docker build --isolation hyperv --no-cache -t print .
Sending build context to Docker daemon  2.048kB
Step 1/4 : FROM mcr.microsoft.com/windows-insider
---> 09a59f60f394
Step 2/4 : SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]
---> Running in 59680f017c12
Removing intermediate container 59680f017c12
---> 94bce0226b5e
Step 3/4 : RUN Set-Service -Name spooler -StartupType Automatic
---> …
```
> Add Dockerfile for Windows spooler

- node/10/Dockerfile
- node/10/README.md
- node/10/build-tools/Dockerfile
- node/10/build-tools/Dockerfile.insider
- node/10/nano/Dockerfile
- node/10/pure/Dockerfile
- node/build.ps1
- node/push.ps1
- node/test.ps1
- node/update.sh
- Revert adding git-lfs #352 due to problems which I can't solve easily
- Update Node.js 10.10.0
- Update Yarn 1.9.4
- Update Git 2.18.0
> Update Node.js 10.10.0

- docker-cli/Dockerfile
- docker-cli/Dockerfile.insider
- Update Docker CLI 18.06.1-ce
- Update Dockerfile for Insider 17744
> Update Docker CLI 18.06.1-ce

- traefik/Dockerfile
- traefik/Dockerfile.1709
- traefik/Dockerfile.insider
- Update Traefik 1.6.6
- Add Dockerfile for Insider 17744
> Update Traefik 1.6.6 + add Insider 17744

- consul/Dockerfile
- consul/README.md
- consul/push.ps1
Update to latest Consul 1.4.0
Add 1803 and 1809/2019 image to manifest list.
> Update Consul 1.4.0, rebase 1809 image

- traefik/Dockerfile
- traefik/Dockerfile.1709
- traefik/Dockerfile.1803
- traefik/Dockerfile.1809
- traefik/Dockerfile.insider
- traefik/insider/Dockerfile
- traefik/insider/README.md
- traefik/insider/docker-compose.yml
- traefik/insider/traefik.toml
- Update base images to mcr
- Update Traefik 1.7.7
- Play with insider 18298
> Update Traefik 1.7.7

- webserver/Dockerfile
- webserver/push.ps1
Build the mini webserver as manifest list for all Windows OS base images.
> Create manifest list

- chocolatey/build.ps1
- chocolatey/push.ps1
> Chocolatey 0.10.13

- openssh/Dockerfile
- openssh/README.md
- openssh/build.ps1
- openssh/install-openssh.ps1
- openssh/push.ps1
- openssh/test.ps1
Prepare a Docker image with Microsoft's OpenSSH port to have an easy test environment
Useful to setup a test environment for https://github.com/inspec/train/issues/419
> Add openssh image

- winrm/Dockerfile
- winrm/README.md
- winrm/build.ps1
- winrm/push.ps1
- winrm/test.ps1
After adding an OpenSSH image with #407 here is another image with WinRM enable and a test user `User03` with `Passw0rd` enabled.
> Add WinRM image

- msys2/Dockerfile
- msys2/README.md
Small test environment for #30 / https://github.com/msys2/MSYS2-packages/issues/1490
> Test msys2

- traefik/Dockerfile.1809
can't connect to the Docker engine otherwise, see #410
> Run as containeradministrator

- webserver/build.ps1
- webserver/push.ps1
- webserver/test.ps1
There is now `mcr.microsoft.com/windows/nanoserver:1903`, so we can add it to the manifest list.
> Add 1903 image to manifest list

- registry/Dockerfile
- registry/build.ps1
- registry/config.yml
- registry/local-host-testing.md
* Update registry image to use the [distribution repo](https://github.com/distribution/distribution)
* Update sample config
* Add local host testing notes
> check registry with docker distribution + nano
